### ISSUE TITLE
remove gem mysql2

### ISSUE THREAD

**Issue by penguinwokrs** [ota42y/gemicoma#89]
postgresを利用するのであれば、mysql2のgemを削除したいです。

また、環境によってはopensslの問題が発生する可能性があるため、利用しないのであれば、削除するほうが良さそうです。

```
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ota42y** [comment]
https://github.com/ota42y/gemicoma/pull/99/files
fixed
